/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/editors": {
    get: operations["all_editors_get"];
    post: operations["create_editor_editors_post"];
  };
}

export interface components {
  schemas: {
    EditorsBase: {
      name: string;
      cidade: string;
      estado: string;
      email: string;
      nascimento: string;
      preview?: string;
      description?: string;
      skills?: components["schemas"]["UserSkills"][];
    };
    HTTPValidationError: {
      detail?: components["schemas"]["ValidationError"][];
    };
    UserSkills: {
      skill_name: string;
      level: number;
    };
    ValidationError: {
      loc: string[];
      msg: string;
      type: string;
    };
  };
}

export interface operations {
  all_editors_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  create_editor_editors_post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditorsBase"][];
      };
    };
  };
}

export interface external {}
